### PR TITLE
3-As a receiver, I should be redirected to another page of questions when I click "I don't know"

### PR DESCRIPTION
**Pull request by PriscilaAlfaro**

### CODE REVIEW

**Comment by miclovich** [comment]
[#3 As a receiver, I should be redirected to another page of questions when I click "I don't know"](https://trello.com/c/RMADNiwi/73-3-as-a-receiver-i-should-be-redirected-to-another-page-of-questions-when-i-click-i-dont-know)

**Review by GayathriVaradan — APPROVED** [review]

**Review by aleksandra-midor — DISMISSED** [review]

**Review by GayathriVaradan — COMMENTED** [review]
Do we need Receiver Q2 in navLinks in  the  file src/components/Menu/index.js (Line25)

**Review by GayathriVaradan — COMMENTED** [review]
In src/App.js, line 64, the link is given as the image link(.jpg file). 
In src/pages/ReceiverOpinionQ2/ProductInformation.js, line 22 you are passing the link which is a .jpg file. I am following till there. But in line 40, are you passing the .jpg file or the product link? 
Its a bit ambiguous there.

**Review by GayathriVaradan — COMMENTED** [review]
It was my understaing that we are not using miragejs in our project now. Is there a reason why you have added server.js from mirage?

**Comment by PriscilaAlfaro** [comment]
@GayathriVaradan I already applied the changes. Please check.

**Review by GayathriVaradan — COMMENTED** [review]
imageUrl declaration is removed in line 45 in the file src/App.js. Dont we need it to be declared?

**Comment by PriscilaAlfaro** [comment]
> imageUrl declaration is removed in line 45 in the file src/App.js. Dont we need it to be declared?

@GayathriVaradan I added the imageUrl,  please check again.

**Review by GayathriVaradan — DISMISSED** [review]

**Review by thasneemmanaf — COMMENTED** [review]
Do we need 'index' in the import statement in line 9 in App.js?

**Comment by PriscilaAlfaro** [comment]
> Do we need 'index' in the import statement in line 9 in App.js?

Yes, because that is the path of my component.

**Comment by thasneemmanaf** [comment]
> > Do we need 'index' in the import statement in line 9 in App.js?
> 
> @thasneemmanaf Yes, because that is the path of my component.

If your component is inside 'index.js' file, we don't need to explicitly specify that in the import statement. Please check the import statement of others

**Comment by PriscilaAlfaro** [comment]
> > > Do we need 'index' in the import statement in line 9 in App.js?
> > 
> > 
> > @thasneemmanaf Yes, because that is the path of my component.
> 
> @PriscilaAlfaro If your component is inside 'index.js' file, we don't need to explicitly specify 'index' file in the import statement path. You can refer other import statements in App.js

@thasneemmanaf I changed the index for standard purposes.

**Review by meerajm — DISMISSED** [review]

**Review by GayathriVaradan — APPROVED** [review]

**Review by meerajm — APPROVED** [review]

**Pull request merged**
